const products = [
    // Alcool
    { img: "img/poliakov-20cl.jpg", alt: "Poliakov 20cl", name: "Poliakov 20cl", price: "5,95", type: "Alcool" },
    { img: "img/poliakov-70cl.jpeg", alt: "Poliakov 70cl", name: "Poliakov 70cl", price: "16.90", type: "Alcool" },
    { img: "img/J&B-70cl.jpeg", alt: "J&B 70cl", name: "J&B 70cl", price: "21.90", type: "Alcool" },
    { img: "img/William-70cl.jpeg", alt: "William Lawson's 70cl", name: "William Lawson's 70cl", price: "19.80", type: "Alcool" },
    { img: "img/JackDaniel-70cl.jpeg", alt: "Jack Daniel's 70cl", name: "Jack Daniel's 70cl", price: "29.50", type: "Alcool" },
    { img: "img/Azur-1L.jpeg", alt: "Azur 1L", name: "Azur 1L", price: "26.90", type: "Alcool" },
    { img: "img/Azur-1L.jpeg", alt: "Azur 70cl", name: "Azur 70cL", price: "19.90", type: "Alcool" },
    { img: "img/CaptainMorganSpicedGold-70cl.jpeg", alt: "Captain Morgan Spiced Gold 70cl", name: "Captain Morgan Spiced Gold 70cl", price: "19.90", type: "Alcool" },
    { img: "img/Rhum3riviere-70cl.jpeg", alt: "Rhum Trois rivière 70cl", name: "Rhum Trois rivière 70cl", price: "19.50", type: "Alcool" },
    { img: "img/GinGordon-70cl.jpeg", alt: "Gin Gordon’s 70cl", name: "Gin Gordon’s 70cl", price: "19.90", type: "Alcool" },
    { img: "img/TequilaSanJose-70cl.jpeg", alt: "Tequila San José 70cl", name: "Tequila San José 70cl", price: "21.90", type: "Alcool" },
    { img: "img/MartiniBlanc-1L.jpeg", alt: "Martini Blanc 1L", name: "Martini Blanc 1L", price: "13.90", type: "Alcool" },
    { img: "img/MartiniRosso-1L.jpeg", alt: "Martini Rouge 1L", name: "Martini Rouge 1L", price: "13.90", type: "Alcool" },
    { img: "img/Jameson-70cl.jpeg", alt: "Jameson 70cl", name: "Jameson 70cl", price: "28.95", type: "Alcool" },
    { img: "img/ClanCampbell-70cl.jpeg", alt: "Clan Campbell 70cl", name: "Clan Campbell 70cl", price: "19.95", type: "Alcool" },
    { img: "img/Label5-70cl.jpeg", alt: "Label 5 20cl", name: "Label 5 20cl", price: "6.95", type: "Alcool" },
    { img: "img/ClanCampbell-20cl.jpeg", alt: "Clan Campbell 20cl", name: "Clan Campbell 20cl", price: "7.50", type: "Alcool" },
    { img: "img/RhumBlanc-20cl.jpeg", alt: "Rhum Blanc 20cl", name: "Rhum Blanc 20cl", price: "5.50", type: "Alcool" },
    { img: "img/RhumAmbre-70cl.jpeg", alt: "Rhum Ambré 20cl", name: "Rhum Ambré 20cl", price: "5.50", type: "Alcool" },
    { img: "img/ChampagneNicolasFeuillate-75cl.jpeg", alt: "Champagne Nicolas Feuillatte 75cl", name: "Champagne Nicolas Feuillatte 75cl", price: "29.90", type: "Alcool" },

    // Boissons
    { img: "img/boisson-33cl.jpg", alt: "Boisson 33cl", name: "Boisson 33cl", price: "1.20", type: "Boissons" },
    { img: "img/Boisson-50cl.png", alt: "Boisson 50cl", name: "Boison 50cl", price: "1.90", type: "Boissons" },
    { img: "img/cristaline-50cl.jpeg", alt: "Cristaline 50cl", name: "Cristaline 50cl", price: "0.50", type: "Boissons" },
    { img: "img/redbull-25cl.jpeg", alt: "Red Bull 25cl", name: "Red Bull 25cl", price: "2.20", type: "Boissons" },
    { img: "img/monster-50cl.jpeg", alt: "Monster 50cl", name: "Monster 50cl", price: "2.50", type: "Boissons" },
    
    //Gateaux

    { img: "img/luprinceloriginal.png", alt: "Lu Prince L'Original", name: "Lu Prince L'Original", price: "2.25", type: "gateaux" },
    { img: "img/bonnemamantartelettecitron.jpeg", alt: "Bonne Maman Tartelette Citron", name: "Bonne Maman Tartelette Citron", price: "2.85", type: "gateaux" },
    { img: "img/bonnemamantarteletteschococarame.jpeg", alt: "Bonne Maman Tartelettes Choco Caramel", name: "Bonne Maman Tartelettes Choco Caramel", price: "2.85", type: "gateaux" },
    { img: "img/lubarquettefraise.jpeg", alt: "Lu Barquette Fraise", name: "Lu Barquette Fraise", price: "1.95", type: "gateaux" },
    { img: "img/lubarquettechocolat.jpeg", alt: "Lu Barquette Chocolat", name: "Lu Barquette Chocolat", price: "1.95", type: "gateaux" },
    { img: "img/lugranolacookies.jpeg", alt: "Lu Granola Cookies", name: "Lu Granola Cookies", price: "2.85", type: "gateaux" },
    { img: "img/lupepitopepites.jpeg", alt: "Lu Pepito Pépites", name: "Lu Pepito Pépites", price: "2.85", type: "gateaux" },
    { img: "img/lupepito.jpeg", alt: "Lu Pepito", name: "Lu Pepito", price: "2.35", type: "gateaux" },
    { img: "img/lupetitecolier.png", alt: "Lu Petit Écolier", name: "Lu Petit Écolier", price: "2,65", type: "gateaux" },
    { img: "img/lugranola.jpeg", alt: "Lu Granola", name: "Lu Granola", price: "2.65", type: "gateaux" },
    { img: "img/kercadelacpaletsbreton.png", alt: "Ker Cadelac Palets Breton", name: "Ker Cadelac Palets Breton", price: "4,50", type: "gateaux" },
    { img: "img/biscuiteriedelabbayegalette normandes 175g.jpeg", alt: "Biscuiterie de l'Abbaye Galette Normande", name: "Galette Normande", price: "2.95", type: "gateaux" },
    { img: "img/biscuiteriedelabbayesableabbaye175g.jpeg", alt: "Biscuiterie de l'Abbaye Sablé Abbaye", name: "Sablé Abbaye", price: "2.85", type: "gateaux" },
    { img: "img/biscuiteriedelabbayesabledantan175g.jpeg", alt: "Biscuiterie de l'Abbaye Sablé d'Antan", name: "Sablé d'Antan", price: "2.95", type: "gateaux" },
    { img: "img/stmichelgrandegalette.jpeg", alt: "St Michel Grande Galette", name: "St Michel Grande Galette", price: "2.95", type: "gateaux" },
    { img: "img/speculos2x125g.png", alt: "Speculos 2x125g", name: "Speculos", price: "2.65", type: "gateaux" },
    { img: "img/stmichelmadeleine250g.jpeg", alt: "St Michel Madeleine 250g", name: "St Michel Madeleine", price: "3.50", type: "gateaux" },
    { img: "img/brossardcakefruit.png", alt: "Brossard Cake aux Fruits", name: "Brossard Cake aux Fruits", price: "3.95", type: "gateaux" },
    { img: "img/luchamonix.jpeg", alt: "Lu Chamonix", name: "Lu Chamonix", price: "2.95", type: "gateaux" },
    { img: "img/lupetitcoeur125.jpeg", alt: "Lu Petit Coeur", name: "Lu Petit Coeur", price: "1.95", type: "gateaux" },
    { img: "img/oreo176G.jpeg", alt: "Oreo 176g", name: "Oreo", price: "2.65", type: "gateaux" },
    { img: "img/bonnemamanpetitfeuillete.png", alt: "Bonne Maman Petit Feuilleté", name: "Bonne Maman Petit Feuilleté", price: "3.95", type: "gateaux" },
    { img: "img/bonnemamanmadelainecho.jpeg", alt: "Bonne Maman Madeleine Chocolat", name: "Bonne Maman Madeleine Chocolat", price: "4.80", type: "gateaux" },
    { img: "img/bonnemamanpetitmuffinchocolat235.png", alt: "Bonne Maman Petit Muffin Chocolat", name: "Bonne Maman Petit Muffin Chocolat", price: "3.90", type: "gateaux" },
    { img: "img/bonnemamanpetitmuffinvanile235.png", alt: "Bonne Maman Petit Muffin Vanille", name: "Bonne Maman Petit Muffin Vanille", price: "3.90", type: "gateaux" },
    { img: "img/mikado100g.jpeg", alt: "Mikado 100g", name: "Mikado", price: "2.65", type: "gateaux" },
    { img: "img/napolitainlu.jpeg", alt: "Napolitain Lu", name: "Napolitain", price: "2.95", type: "gateaux" },
    { img: "img/savane310g.png", alt: "Savane 310g", name: "Savane", price: "3.50", type: "gateaux" },


    // Bière
    { img: "img/Guiness-50cl.jpeg", alt: "Guiness 50cl", name: "Guiness 50cl", price: "2.70", type: "Biere" },
    { img: "img/86-50cl.jpeg", alt: "8&6", name: "8&6 50cl ", price: "2.00", type: "Biere" },
    { img: "img/1664-50cl.jpeg", alt: "1664 50cl", name: "1664 50cl", price: "2.00", type: "Biere" },
    { img: "img/Heineken-50cl.jpeg", alt: "Heineken 50cl", name: "Heineken 50cl", price: "2.00", type: "Biere" },
    { img: "img/LaGoudale-50cl .jpeg", alt: "La Goudale 50cl", name: "La Goudale 50cl", price: "2.50", type: "Biere" },
    { img: "img/Leffe-50cl.jpeg", alt: "Leffe 50cl", name: "Leffe 50cl", price: "2.70", type: "Biere" },
    { img: "img/Sombrero-50cl.png", alt: "sombrero", name: "Sombrero 50cl", price: "2.00", type: "Biere" },
    { img: "img/DesperadosRed-50cl.jpeg", alt: "despered50cl", name: "DESPERADOS RED 50cl", price: "2.80", type: "Biere" },
    { img: "img/Desperados-50cl.jpeg", alt: "despe50cl", name: "DESPERADOS 50cl", price: "2.60", type: "Biere" },
    { img: "img/Desperados-65cl.jpeg", alt: "despe65cl", name: "DESPERADOS 65cl", price: "3.95", type: "Biere" },
    { img: "img/Heineken-12x25cl.jpeg", alt: "Heineken 12x25cl", name: "Heineken 12x25cl", price: "12.60", type: "Biere" },
    { img: "img/Heineken-6x25cl.jpeg", alt: "Heineken 6x25cl", name: "Heineken 6x25cl", price: "6.50", type: "Biere" },
    { img: "img/1664-12x25cl.jpeg", alt: "1664 12x25cl", name: "1664 12x25cl", price: "12.60", type: "Biere" },
    { img: "img/1664-6x25cl.png", alt: "1664 6x25cl", name: "1664 6x25cl", price: "6.50", type: "Biere" },
    { img: "img/LaGoudaleAmbree-6x25cl.png", alt: "La Goudale Ambrée 6x25cl", name: "La Goudale Ambrée 6x25cl", price: "6.95", type: "Biere" },
    { img: "img/LaGoudaleBlonde-6x25cl.jpeg", alt: "La Goudale Blonde 6x25cl", name: "La Goudale Blonde 6x25cl", price: "6.95", type: "Biere" },
    { img: "img/LeffeBlonde-6x25cl.jpeg", alt: "Leffe Blonde 6x25cl", name: "Leffe Blonde 6x25cl", price: "8.90", type: "Biere" },
    { img: "img/LeffeRituel-6x25cl.jpeg", alt: "lefferituelpack", name: "LEFFE RITUEL 6x25cl", price: "8.90", type: "Biere" },  
    { img: "img/LeffeTripleBlonde-6x25cl.jpeg", alt: "leffetriple", name: "", price: "8.90", type: "Biere" },
    { img: "img/Affligen-6x25cl.jpeg", alt: "affligenpack", name: "AFFLIGEN 6x25cl", price: "7.50", type: "Biere" }, 
    { img: "img/Pelforth-6x25cl.jpeg", alt: "pelforthpack", name: "PELFORTH 6x25cl", price: "5.95", type: "Biere" },
    { img: "img/Jenlain-6x25cl.png", alt: "jenlain", name: "JENLAIN 6x25cl", price: "7.95", type: "Biere" },
    { img: "img/Skoll-3x33cl.jpeg", alt: "Skoll", name: "SKOLL 3x33cl", price: "7.95", type: "Biere" },





    // Yaourt 
    { img :"img/activia.jpeg", alt: "activia", name: "ACTIVIA NATURE 4x125g", price: "2.25", type: "Yaourt" },
    { img :"img/veloute.jpeg", alt: "veloute", name: "VELOUTE NATURE 4x125g", price: "1.95", type: "Yaourt" },
    { img :"img/gervita.jpeg", alt: "gervita", name: "GERVITA 4x125g", price: "2.65", type: "Yaourt" },
    { img :"img/fjord.jpeg", alt: "fjord", name: "FJORD NATURE 4x125g", price: "2.55", type: "Yaourt" },
    { img :"img/rizaulait.jpeg", alt: "rizaulait", name: "RIZ AU LAIT SAVEUR VANILLE 4x115g", price: "2.65", type: "Yaourt" },
    { img :"img/cremebrulee.jpeg", alt: "cremebrule", name: "CREME BRULEE VANILLE", price: "3.50", type: "Yaourt" },
    { img :"img/fraismalo0.jpeg", alt: "fraismalo0%", name: "FROMAGE FRAIS MALO 0% 4x100g", price: "2.65", type: "Yaourt" },
    { img :"img/fraismalo20.jpeg", alt: "fraismalo20%", name: "FROMAGE FRAIS MALO 20% 4x100g", price: "2.65", type: "Yaourt" },
    { img :"img/yaos.jpeg", alt: "yaos", name: "YAOURT GRECQUE 4x150g", price: "3.50", type: "Yaourt" },
    { img :"img/danettechocolat.jpeg", alt: "danettechocolat", name: "DANETTE CHOCOLAT 4x125g", price: "2.65", type: "Yaourt" },
    { img :"img/danettevanille.jpeg", alt: "danettevanille", name: "DANETTE VANILLE 4x125g", price: "2.65", type: "Yaourt" },
    { img :"img/maminovaananas.jpeg", alt: "mamienovaananas", name: "MAMIE NOVA ANANAS 2x150g", price: "2.25", type: "Yaourt" },
    { img :"img/maminovafraise.jpeg", alt: "mamienovafraise", name: "MAMIE NOVA FRAISE 2x150g", price: "2.25", type: "Yaourt" },
    { img :"img/maminovapeche.jpeg", alt: "mamienovapeche", name: "MAMIE NOVA PECHE 2x150g", price: "2.25", type: "Yaourt" },
    { img :"img/mousseauchocolat.jpeg", alt: "moussechoco", name: "MOUSSE AU CHOCOLAT", price: "2.20", type: "Yaourt" },
    { img :"img/viennoiscafe.jpeg", alt: "vienoicafe", name: "VIENNOIS CAFE 4x100g", price: "2.65", type: "Yaourt" },
    { img :"img/viennoiscafe.jpeg", alt: "vienoicafe", name: "VIENNOIS CHOCOLAT 4x100g", price: "2.65", type: "Yaourt" },
    { img :"img/compotepommebanane.jpeg", alt: "compotepomme", name: "COMPOTE POMME BANANE 4x100g", price: "2.25", type: "Yaourt" },
    { img :"img/compotepommeframboise.jpeg", alt: "compoteframboise", name: "COMPOTE POMME FRAMBOISE 4x100g ", price: "2.25", type: "Yaourt" },
    { img :"img/compotepommepoire.jpeg", alt: "compotepommepoire", name: "COMPOTE POMME POIRE 4x100g", price: "2.25", type: "Yaourt" },
    
    

    //Beurre et Fromage
    { img :"img/beurrepresidentdemisel.jpeg", alt: "beurredemiseil", name: "BEURRE PRESIDENT DEMI-SEL 250g", price: "2.95", type: "Cremerie" },
    { img :"img/beurrepresidentdoux.jpeg", alt: "beureedoux", name: "BEURRE PRESIDENT DOUX 250g", price: "2.95", type: "Cremerie" },
    { img :"img/omega3.jpeg", alt: "margarineomega3", name: "ST HUBERT OMEGA3 250g", price: "3.35", type: "Cremerie" },
    { img :"img/Plantafin.jpeg", alt: "margarineplantafin", name: "PLANTAFIN 250g", price: "2.85", type: "Cremerie" },
    { img :"img/primevere.jpeg", alt: "margarineprimevere", name: "PRIMEVERE 250G", price: "3.25", type: "Cremerie" },
    { img :"img/fromagepresident.jpeg", alt: "camenbertpresident", name: "PRESIDENT 250G", price: "2.95", type: "Cremerie" },
    { img :"img/fromagecoeurdelion.jpeg", alt: "camenbertcoeurdelion", name: "COEUR DE LION 250g", price: "2.95", type: "Cremerie" },
    { img :"img/fromagelerustique.jpeg", alt: "camembertlerustique", name: "LE RUSTIQUE 250g", price: "3.90", type: "Cremerie" },
    { img :"img/fromagel'ortolan.jpeg", alt: "cambertlortolan", name: "L'ORTOLAN 220g", price: "3.95", type: "Cremerie" },
    { img :"img/fromagechausséeauxmoines.jpeg", alt: "camembertchausse", name: "CHAUSSEE AUX MOINES 340g", price: "4.95", type: "Cremerie" },
    { img :"img/fromagebriedesducs.jpeg", alt: "briedesducs", name: "BRIE DES DUCS", price: "xxx", type: "Cremerie" }, 
    { img :"img/fromagecapricedesdieux.jpeg", alt: "capricedesdieux", name: "CAPRICE DES DIEUX 200g", price: "", type: "Cremerie" },
    { img :"img/roquefortsociete.jpeg", alt: "roquefort", name: "ROQUEFORT SOCIETE 100g", price: "3.50", type: "Cremerie" },
    { img :"img/fromagechevresoignon.jpeg", alt: "chevresognon", name: "BUCHE CHEVRE STE MAURE 200g", price: "3.50", type: "Cremerie" },
    { img :"img/feta.jpeg", alt: "feta", name: "FETA 200g", price: "4.95", type: "Cremerie" },
    { img :"img/feta.jpeg", alt: "mozzarella", name: "MOZZARELLA 125g", price: "2.25g", type: "Cremerie" },
    { img :"img/mascarpone.jpeg", alt: "mascarpone", name: "MASCARPONE 250g", price: "4.95", type: "Cremerie" },
    { img :"img/parmesan.jpeg", alt: "parmesan", name: "PERMIGIANO REGGIANO 60g", price: "2.65g", type: "Cremerie" },
    { img :"img/fromagerape.jpeg", alt: "fromagerape", name: "EMMENTAL RAPE 200g", price: "2.95", type: "Cremerie" },

    { img :"img/leerdammer.jpeg", alt: "leerdamer ", name: "LEERDAMMER 200G 8TR", price: "4.50", type: "Cremerie" },
    { img :"img/fromageemmental.jpeg", alt: "emmental", name: "COEUR DE MEULE EMMENTAL 250g", price: "4.95", type: "Cremerie" },
    { img :"img/fromageconté.jpeg", alt: "comteentremont", name: "ENTREMONT COMTE 200g", price: "5,50", type: "Cremerie" },
    { img :"img/philadelphia.jpeg", alt: "philadelphia", name: "PHILADELPHIA 150g", price: "2.95", type: "Cremerie" },
    { img :"img/fromagekiri.jpeg", alt: "kiri", name: "KIRI 8PR 144G", price: "3.50", type: "Cremerie" },
    { img :"img/fromagevachequirit.jpeg", alt: "vachequirit", name: "VACHE QUI RIT 12PR 192g", price: "3.50", type: "Cremerie" },
    { img :"img/Tranchecheddar.jpeg", alt: "tranchetteburger", name: "TRANCHETTE BURGER CHEDDAR 200g", price: "2.65", type: "Cremerie" },
    { img :"img/croqueemmental.jpeg", alt: "tranchetteemmental", name: "TRANCHETTE EMMENTAL 200g", price: "2.65", type: "Cremerie" },

    { img :"img/panzanibolognaise.jpeg", alt: "", name: "Sauce Bolognaise Panzani 500g", price: "3.95", type: "Pate" },
    { img :"img/panzanicoquillette.jpeg", alt: "", name: "Coquillette Panzani 500g", price: "1.95", type: "Pate" },
    { img :"img/panzanicouderaye.jpeg", alt: "", name: "Coude Rayé Panzani 500g", price: "1.95", type: "Pate" },
    { img :"img/panzanifarfale.jpeg", alt: "", name: "Farfale Panzani 500g", price: "1.95", type: "Pate" },
    { img :"img/panzanipesto.jpeg", alt: "", name: "Sauce Pesto Panzani 200g", price: "2.95", type: "Pate" },
    { img :"img/panzanipiperigate.jpeg", alt: "", name: "Pipe Rigate Panzani 500g", price: "1.95", type: "Pate" },
    { img :"img/panzaniprovencale.png", alt: "", name: "Sauce Provencale Panzani 425g", price: "3.25", type: "Pate" },
    { img :"img/panzaniserpenntini.jpeg", alt: "", name: "Serpentini Panzani 500g", price: "1.95", type: "Pate" },
    { img :"img/panzanitomacouli.jpeg", alt: "", name: "Tomacouli Panzani 500g", price: "2.25", type: "Pate" },
    { img :"img/zapettitomate.jpeg", alt: "", name: "Sauce Tomate Cuisinée 2x190g", price: "2.65", type: "Pate" },
    { img :"img/lessieurmayopot.jpeg", alt: "", name: "Mayonnaise Pot Lessieur 235g", price: "2.25", type: "Pate" },
    { img :"img/lessieurmayotube.jpeg", alt: "", name: "Mayonnaise Tube Lessieur 175g", price: "1.85", type: "Pate" },
    { img :"img/maillecornichon.jpeg", alt: "", name: "Cornichon Maille 400g", price: "4.50", type: "Pate" },
    { img :"img/beneidctamayocitron.jpeg", alt: "", name: "Sauce Mayo-Citron Bénédidcta 255g", price: "2.85", type: "Pate" },
    { img :"img/benedictabearnaise.png", alt: "", name: "Sauce Béarnaise Bénédidcta 255g", price: "2.85", type: "Pate" },
    { img :"img/barillaarrabiatata.jpeg", alt: "", name: "Sauce Arrabiata Barilla 400g", price: "3.90", type: "Pate" },
    { img :"img/bellefrancecoulitomate.jpeg", alt: "", name: "Couli de Tomates 420g", price: "2.25", type: "Pate" },
    { img :"img/amorasamourai.jpeg", alt: "", name: "Sauce Samourai Amora", price: "2.65", type: "Pate" },
    { img :"img/amoraketchup.jpeg", alt: "", name: "Ketchup Amora", price: "2.65", type: "Pate" },
    { img :"img/amoramoutardetube.jpeg", alt: "", name: "Moutarde Forte Amora", price: "2.65", type: "Pate" },
    { img :"img/amoramoutardepot.jpeg", alt: "", name: "Moutarde de Dijon Forte Amora 355g ", price: "2.65", type: "Pate" },
    { img :"img/amorabbq.jpeg", alt: "", name: "Sauce BBQ Amora", price: "2.65", type: "Pate" },


    // Plat préparé
    { img: "img/williamblanquette.jpeg", alt: "Blanquette de veau William", name: "Barquette Blanquette de veau", price: "4.90", type: "Plat Préparé" },
    { img: "img/williamboeufbourgui.jpeg", alt: "Bœuf bourguignon William", name: "Barquette Bœuf Bourguignon", price: "4.95", type: "Plat Préparé" },
    { img: "img/williamtartiflette.jpeg", alt: "Tartiflette William", name: "Barquette Tartiflette", price: "4.95", type: "Plat Préparé" },
    { img: "img/williamcolin.jpeg", alt: "Filet de colin William", name: "Barquette Filet de Colin", price: "4.80", type: "Plat Préparé" },
    { img: "img/williamsaurinboeufbourgui.jpeg", alt: "Bœuf bourguignon William Saurin", name: "Cocotte Bœuf Bourguignon William Saurin", price: "5.80", type: "Plat Préparé" },
    { img: "img/williamsaurincassouletcanard.jpeg", alt: "Cassoulet au canard William Saurin", name: "Cocotte Cassoulet au Canard", price: "5.80", type: "Plat Préparé" },
    { img: "img/williamsaurinpoulet.jpeg", alt: "Poulet rôti William Saurin", name: "Cocotte Poulet Rôti", price: "5.80", type: "Plat Préparé" },
    { img: "img/garbitcouscous.jpeg", alt: "Couscous Garbit", name: "Barquette Couscous", price: "4.80", type: "Plat Préparé" },
    { img: "img/bellefrancecassoulet1:2.jpeg", alt: "Cassoulet 1/2 Belle France", name: "Cassoulet 420g", price: "2.25", type: "Plat Préparé" },
    { img: "img/bellefrancechoucroute1:2.jpeg", alt: "Choucroute 1/2 Belle France", name: "Choucroute 400g", price: "2.85", type: "Plat Préparé" },
    { img: "img/bellefrancepetitsale400g.jpeg", alt: "Petit salé 400g Belle France", name: "Petit Salé 420g", price: "2.95", type: "Plat Préparé" },
    { img: "img/bellefranceraviolibolo400g.jpeg", alt: "Ravioli à la bolognaise 400g Belle France", name: "Ravioli Bolognaise 400g", price: "2.95", type: "Plat Préparé" },
    { img: "img/bellefranceraviolipurboeuf400g.jpeg", alt: "Ravioli pur bœuf 400g Belle France", name: "Ravioli Pur Bœuf 400g", price: "2.65", type: "Plat Préparé" },
    { img: "img/bellefrancesaucisselentille420g.jpeg", alt: "Saucisses aux lentilles 420g Belle France", name: "Saucisses Lentilles 420g", price: "2.95", type: "Plat Préparé" },
    { img: "img/bellefrancechiliconcarne.jpeg", alt: "Chili con carne Belle France", name: "Chili Con Carne 400g", price: "2.85", type: "Plat Préparé" },
    { img: "img/bellefrancecassoulet44.jpeg", alt: "Cassoulet 4/4 Belle France", name: "Cassoulet 800g", price: "3.95", type: "Plat Préparé" },
    { img: "img/bellefrancechocroute4:4.jpeg", alt: "Choucroute 4/4 Belle France", name: "Choucroute 800g", price: "4.50", type: "Plat Préparé" },
    { img: "img/bellefrancepetitsale800g.jpeg", alt: "Petit salé 800g Belle France", name: "Petit Salé 800g", price: "4.95", type: "Plat Préparé" },
    { img: "img/bellefranceraviolipurboeuf800g.jpeg", alt: "Ravioli pur bœuf 800g Belle France", name: "Ravioli Pur Bœuf 800g", price: "4.50", type: "Plat Préparé" },
    { img: "img/bellefrancetaviolibolo800g.jpeg", alt: "Ravioli à la bolognaise 800g Belle France", name: "Ravioli Bolognaise 800g", price: "4.80", type: "Plat Préparé" },
    { img: "img/bellefrancepaela.jpeg", alt: "Paella Belle France", name: "Paella 1kg", price: "4.95", type: "Plat Préparé" },
    { img: "img/bellefrancesaucisselentille840g.jpeg", alt: "Saucisses aux lentilles 840g Belle France", name: "Saucisses Lentilles 840g", price: "4.50", type: "Plat Préparé" },

    //Chips
    { img: "img/LaysBarbecue.jpeg", alt: "Chips barbecue Lay's", name: "Lay's Barbecue", type: "Chips", price: "2.65" },
    { img: "img/LaysPaysannes.jpeg", alt: "Chips paysannes Lay's", name: "Lay's Paysannes", type: "Chips", price: "2.65" },
    { img: "img/LaysALancienne.jpeg", alt: "Chips à l'ancienne Lay's", name: "Lay's À l'Ancienne", type: "Chips", price: "2.65" },
    { img: "img/LaysNature.jpeg", alt: "Chips nature Lay's", name: "Lay's Nature", type: "Chips", price: "2.65" },
    { img: "img/bretzselvinaigre.png", alt: "Chips sel et vinaigre Bretz", name: "Bretz Chips Sel et Vinaigre", type: "Chips", price: "2.25" },
    { img: "img/bretzpommefrite.png", alt: "Chips goût pomme frite Bretz", name: "Bretz Chips Goût Pomme Frite", type: "Chips", price: "2.25" },
    { img: "img/bretzPoulet.png", alt: "Chips goût poulet Bretz", name: "Bretz Chips Goût Poulet", type: "Chips", price: "2.25" },
    { img: "img/bretzchevre.png", alt: "Chips goût chèvre Bretz", name: "Chips Goût Chèvre", type: "Chips", price: "2.25" },
    { img: "img/bretzpizza.png", alt: "Chips goût pizza Bretz", name: "Chips Goût Pizza", type: "Chips", price: "2.25" },
    { img: "img/tuilebacon.jpeg", alt: "Tuiles goût bacon", name: "Tuiles Bacon", type: "Chips", price: "2.65" },
    { img: "img/tuilespaprika.jpeg", alt: "Tuiles goût paprika", name: "Tuiles Paprika", type: "Chips", price: "2.65" },
    { img: "img/tuilesepice.png", alt: "Tuiles goût épices", name: "Tuiles Épices", type: "Chips", price: "2.65" },
    { img: "img/tuileSale.jpeg", alt: "Tuiles salées", name: "Tuiles Salées", type: "Chips", price: "2.65" },
    { img: "img/tuilecremeoigon.jpeg", alt: "Tuiles crème et oignon", name: "Tuiles Crème et Oignon", type: "Chips", price: "2.65" },
    { img: "img/DoritosSweetchili.jpeg", alt: "Doritos goût sweet chili", name: "Doritos Sweet Chili", type: "Chips", price: "2.95" },
    { img: "img/bellefrancepistachegrilleetsalees.jpeg", alt: "Pistaches grillées et salées Belle France 125g", name: "Pistaches Grillées et Salées 125g", type: "Chips", price: "3.50" },
    { img: "img/bellefrancecacahuetegrilleasec.jpeg", alt: "Cacahuètes grillées à sec Belle France 125g", name: "Cacahuètes Grillées à Sec 125g", type: "Chips", price: "1.90" },
    { img: "img/bellefrancecacahuetegrilleetsalees.jpeg", alt: "Cacahuètes grillées et salées Belle France 250g", name: "Cacahuètes Grillées et Salées 250g", type: "Chips", price: "1.95" },
    { img: "img/bellefrancenoixdecajou.jpeg", alt: "Noix de cajou Belle France", name: "Noix de Cajou 100g", type: "Chips", price: "2.95" },
    { img: "img/curlyclub.jpeg", alt: "Curly Club", name: "Curly CLUB 90g", type: "Chips", price: "2.25" },
    { img: "img/belinminizaa.jpeg", alt: "Mini-Zaa Belin", name: "Minizza Belin 95g", type: "Chips", price: "1.95" },
    { img: "img/tuc.jpeg", alt: "TUC", name: "TUC Original 100g", type: "Chips", price: "1.50" },
    { img: "img/ancelbretzel.png", alt: "Bretzels Ancel", name: "Bretzels 300g", type: "Chips", price: "3.50" },

    //SURGELE

    { img: "img/bellefrancepaelaroyale.jpeg", alt: "Paëlla royale Belle France", name: "Paëlla Royale", type: "Surgelé", price: "6.50" },
    { img: "img/bellefrancerizcantonais.jpg", alt: "Riz cantonais Belle France", name: "Riz Cantonais", type: "Surgelé", price: "4.75" },
    { img: "img/finduscroquettepoisson.jpg", alt: "Croquettes de poisson Findus", name: "Croquettes de Poisson", type: "Surgelé", price: "5.25" },
    { img: "img/mariecolindalaska.png", alt: "Colin d'Alaska Marie", name: "Colin d'Alaska", type: "Surgelé", price: "6.80" },
    { img: "img/bellefrancefiletsdecolondalaska.jpg", alt: "Filets de colin d'Alaska Belle France", name: "Filets de Colin d'Alaska", type: "Surgelé", price: "7.20" },
    { img: "img/bellefrance2coquillesstjacques.jpg", alt: "Coquilles Saint-Jacques Belle France", name: "Coquilles St-Jacques (x2)", type: "Surgelé", price: "5.90" },
    { img: "img/bellefrance4panierfromagedechevre.jpg", alt: "Panier feuilleté fromage de chèvre Belle France", name: "Panier Fromage de Chèvre (x4)", type: "Surgelé", price: "4.50" },
    { img: "img/Bellefrance4panierfeuilletesjambon-emmental.jpg", alt: "Panier feuilleté jambon-emmental Belle France", name: "Panier Jambon-Emmental (x4)", type: "Surgelé", price: "4.75" },
    { img: "img/bellefrance40minifeuilletes.jpg", alt: "Mini feuilletés Belle France (x40)", name: "Mini Feuilletés (x40)", type: "Surgelé", price: "6.30" },
    { img: "img/bellefrancetarte3fromage.jpg", alt: "Tarte aux 3 fromages Belle France", name: "Tarte 3 Fromages", type: "Surgelé", price: "3.95" },
    { img: "img/mariequichelorraine.jpg", alt: "Quiche lorraine Marie", name: "Quiche Lorraine", type: "Surgelé", price: "4.20" },
    { img: "img/MARIE_TARTE_SAUMO.png", alt: "Tarte au saumon Marie", name: "Tarte Saumon", type: "Surgelé", price: "5.50" },
    { img: "img/MarieLasagne.png", alt: "Lasagnes Marie", name: "Lasagnes", type: "Surgelé", price: "4.80" },
    { img: "img/original_buns_burger_.jpg", alt: "Buns burger", name: "Buns Burger", type: "Surgelé", price: "3.50" },
    { img: "img/buns_bolognaise.png", alt: "Buns bolognaise", name: "Buns Bolognaise", type: "Surgelé", price: "3.75" },
    { img: "img/ristorantepizzathon.webp", alt: "Pizza Thon Ristorante", name: "Pizza Thon", type: "Surgelé", price: "4.95" },
    { img: "img/ristorante4fromaggi.webp", alt: "Pizza 4 fromages Ristorante", name: "Pizza 4 Fromages", type: "Surgelé", price: "4.95" },
    { img: "img/ristorantepizzaroyale.webp", alt: "Pizza Royale Ristorante", name: "Pizza Royale", type: "Surgelé", price: "5.10" },

    //HYGIENE 


    //PRODUIT MENAGE 


    //NOURRITURE POUR ANIMAUX


    //PETIT_DEJEUNER 
    { img: "img/cartenoire.jpeg", alt: "Café moulu Carte Noire", name: "Café Carte Noire", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/ricoré.jpeg", alt: "Ricoré mélange de café et de chicorée", name: "Ricoré", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/vanhoutencacao.jpeg", alt: "Cacao en poudre Van Houten", name: "Cacao Van Houten", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/tassimol'orexpresso.jpeg", alt: "Capsules Tassimo L'Or Espresso", name: "Tassimo L'Or Espresso", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/tetleyenglishbreakfast.jpeg", alt: "Thé Tetley English Breakfast", name: "Thé English Breakfast", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/lipton30s.jpeg", alt: "Thé Lipton Yellow Label 30 sachets", name: "Thé Lipton Yellow Label", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/bellefrancepaingrillé.jpeg", alt: "Pain grillé Belle France", name: "Pain Grillé", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/rogerbiscotte.jpeg", alt: "Biscottes Roger", name: "Biscottes Roger", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/krispolisdorés.jpeg", alt: "Biscottes Krispolls Dorées", name: "Biscottes Krispolls Dorées", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/heudebertlabiscotte.jpeg", alt: "Biscottes Heudebert", name: "Biscottes Heudebert", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/sabarot flocondavoine.jpeg", alt: "Flocons d'avoine Sabarot", name: "Flocons d'Avoine", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/nesquik375g.jpeg", alt: "Cacao en poudre Nesquik 375g", name: "Nesquik 375g", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/chocopic375G.jpeg", alt: "Céréales Chocapic 375g", name: "Chocapic 375g", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/tresorchocolait410g.jpeg", alt: "Céréales Trésor chocolat au lait 410g", name: "Trésor Chocolat au Lait", type: "Petit-déjeuner", price: "2.65" },
    { img: "img/tresorchoconoisette41Og.jpeg", alt: "Céréales Trésor chocolat noisette 410g", name: "Trésor Chocolat Noisette", type: "Petit-déjeuner", price: "2.65" },


    //JUS 
    

    // Formule
    { img: "img/Formule10.png", alt: "Formule P1", name: "Formule P1", price: "10.00", type: "Formule" }
];

